//Exporting cultures to be used in index.js
export {cultures};

//Array of objects containing cultures for Humankind and relevant attributes
let cultures = [
    {
        "Era": "Ancient",
        "Culture": "Assyrians",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Raid Masters",
        "Legacy trait info": "+1 Land Movement Speed on Unit, +5 Combat Strength bonus when Ransacking on Army",
        "Emblematic unit": "Assyrian Raiders",
        "Emblematic unit Wiki link": "https://humankind.fandom.com/wiki/Assyrian_Raiders",
        "Emblematic quarter": "Dunnu",
        "Emblematic quarter Wiki link": "https://humankind.fandom.com/wiki/Dunnu",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Ancient",
        "Culture": "Babylonians",
        "Affinity": "Scientist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Brilliant Philosophers",
        "Legacy trait info": "+2 Science per researched technology on Capital.",
        "Emblematic unit": "Ṣäbu Ša Qašti",
        "Emblematic quarter": "Astronomy House",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into 'Collective Minds' mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Ancient",
        "Culture": "Egyptians",
        "Affinity": "Builder",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Grand Planners",
        "Emblematic unit": "Markabata",
        "Emblematic quarter": "Egyptian Pyramid",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into 'Land Raiser' mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Ancient",
        "Culture": "Harappans",
        "Affinity": "Agrarian",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Fertile Inundations",
        "Emblematic unit": "Runner",
        "Emblematic quarter": "Canal Network",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Ancient",
        "Culture": "Hittites",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Lust For War",
        "Emblematic unit": "Gigir",
        "Emblematic quarter": "Awari",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Ancient",
        "Culture": "Mycenaeans",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Brutal upbringing",
        "Emblematic unit": "Promachoi",
        "Emblematic quarter": "Cyclopean Fortress",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Ancient",
        "Culture": "Nubians",
        "Affinity": "Merchant",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Golden Dreams",
        "Emblematic unit": "Ta-Seti Archers",
        "Emblematic quarter": "Meroe Pyramids",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Ancient",
        "Culture": "Olmecs",
        "Affinity": "Aesthete",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Natural Harmony",
        "Emblematic unit": "Javelin Throwers",
        "Emblematic quarter": "Olmec Head",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Ancient",
        "Culture": "Phoenicians",
        "Affinity": "Merchant",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Trading Pioneers",
        "Emblematic unit": "Bireme",
        "Emblematic quarter": "Haven",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Ancient",
        "Culture": "Zhou",
        "Affinity": "Aesthete",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Harmonious Thought",
        "Emblematic unit": "Zhànche",
        "Emblematic quarter": "Confucian School",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Classical",
        "Culture": "Achaemenid Persians",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Cyrus' Shadow",
        "Emblematic unit": "Immortals",
        "Emblematic quarter": "Satrap Palace",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Classical",
        "Culture": "Aksumites",
        "Affinity": "Merchant",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Horn of Plenty",
        "Emblematic unit": "Shotelai",
        "Emblematic quarter": "Great Obelisk",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Classical",
        "Culture": "Carthaginians",
        "Affinity": "Merchant",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Hard Bargainers",
        "Emblematic unit": "War Elephant",
        "Emblematic quarter": "Cothon",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Classical",
        "Culture": "Celts",
        "Affinity": "Agrarian",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Druidic Lore",
        "Emblematic unit": "Gaesati",
        "Emblematic quarter": "Nemeton",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Classical",
        "Culture": "Goths",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Nimble Pillage",
        "Emblematic unit": "Gothic Cavalry",
        "Emblematic quarter": "Tumulus",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Classical",
        "Culture": "Greeks",
        "Affinity": "Scientist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Socratic Methods",
        "Emblematic unit": "Hoplites",
        "Emblematic quarter": "Amphitheatron",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into 'Collective Minds' mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Classical",
        "Culture": "Huns",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Formidable Steeds",
        "Emblematic unit": "Hunnic Horde",
        "Emblematic quarter": "Ordu",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Classical",
        "Culture": "Mauryans",
        "Affinity": "Aesthete",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Guiding Light",
        "Emblematic unit": "Saṃnāhya",
        "Emblematic quarter": "Stūpa",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Classical",
        "Culture": "Maya",
        "Affinity": "Builder",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Tireless Spirit",
        "Emblematic unit": "Noble Javelineers",
        "Emblematic quarter": "K'uh Nah",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into 'Land Raiser' mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Classical",
        "Culture": "Romans",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Legions Finest",
        "Emblematic unit": "Praetorian Guards",
        "Emblematic quarter": "Triumphal Arch",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Medieval",
        "Culture": "Aztecs",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Huitzilopochtli's Legacy",
        "Emblematic unit": "Jaguar Warriors",
        "Emblematic quarter": "Sacrificial Altar",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Medieval",
        "Culture": "Byzantines",
        "Affinity": "Merchant",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Master of Whispers",
        "Emblematic unit": "Varangian Guards",
        "Emblematic quarter": "Hippódromos",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Medieval",
        "Culture": "English",
        "Affinity": "Agrarian",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Serfs' Labor",
        "Emblematic unit": "Longbowmen",
        "Emblematic quarter": "Stronghold",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Medieval",
        "Culture": "Franks",
        "Affinity": "Aesthete",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Crown Lands",
        "Emblematic unit": "Franci Milites",
        "Emblematic quarter": "Scriptorium",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Medieval",
        "Culture": "Ghanaians",
        "Affinity": "Merchant",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Life of Luxury",
        "Emblematic unit": "Meharists",
        "Emblematic quarter": "Luxuries Market",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Medieval",
        "Culture": "Khmer",
        "Affinity": "Builder",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Servants of Magnificence",
        "Emblematic unit": "Dhanvī-gaja",
        "Emblematic quarter": "Baray",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into 'Land Raiser' mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Medieval",
        "Culture": "Mongols",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Mounted Mayhem",
        "Emblematic unit": "Mongol Horde",
        "Emblematic quarter": "Orda",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Medieval",
        "Culture": "Norsemen",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Stormborn",
        "Emblematic unit": "Langskip",
        "Emblematic quarter": "Naust",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Medieval",
        "Culture": "Teutons",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Spurred by Faith",
        "Emblematic unit": "Teutonic Knights",
        "Emblematic quarter": "Kaiserdom",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Medieval",
        "Culture": "Umayyads",
        "Affinity": "Scientist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Learned Friends",
        "Emblematic unit": "Haras",
        "Emblematic quarter": "Grand Mosque",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into 'Collective Minds' mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Early Modern",
        "Culture": "Dutch",
        "Affinity": "Merchant",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Stock Wisdom",
        "Emblematic unit": "Fluyt",
        "Emblematic quarter": "V.O.C Warehouse",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Early Modern",
        "Culture": "Edo Japanese",
        "Affinity": "Aesthete ",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Shogun's Authority",
        "Emblematic unit": "Naginata Samurai",
        "Emblematic quarter": "Tera",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Early Modern",
        "Culture": "Haudenosaunee",
        "Affinity": "Agrarian",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Land of Plenty",
        "Emblematic unit": "Rotiskenrakehte",
        "Emblematic quarter": "Three Sisters Plantation",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Early Modern",
        "Culture": "Joseon",
        "Affinity": "Scientist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Hall of Wothies",
        "Emblematic unit": "Geobukseon",
        "Emblematic quarter": "Seowon",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into 'Collective Minds' mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Early Modern",
        "Culture": "Ming",
        "Affinity": "Aesthete",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Grand Secretariat",
        "Emblematic unit": "Rocket Cart",
        "Emblematic quarter": "Grand Teahouse",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Early Modern",
        "Culture": "Mughals",
        "Affinity": "Builder",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Imperial Magnificence",
        "Emblematic unit": "Gajnal",
        "Emblematic quarter": "Jama Masjid",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into 'Land Raiser' mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Early Modern",
        "Culture": "Ottomans",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Supremacy of Fire",
        "Emblematic unit": "Janissaries",
        "Emblematic quarter": "Sultan Camii",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Early Modern",
        "Culture": "Poles",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Deadly Ramparts",
        "Emblematic unit": "Winged Hussars",
        "Emblematic quarter": "Barbican",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Early Modern",
        "Culture": "Spanish",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Honor and Glory",
        "Emblematic unit": "Conquistadores",
        "Emblematic quarter": "Catedral Gótica",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Early Modern",
        "Culture": "Venetians",
        "Affinity": "Merchant",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Silver Tongues",
        "Emblematic unit": "Galleass",
        "Emblematic quarter": "Botteghe Di Artisti",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Industrial",
        "Culture": "Austro-Hungarians",
        "Affinity": "Aesthete ",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Emperor's Hand",
        "Emblematic unit": "Evidenzbureau Agents",
        "Emblematic quarter": "Opernhaus",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Industrial",
        "Culture": "British",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Colonial Riches",
        "Emblematic unit": "Redcoats",
        "Emblematic quarter": "Colonial Office",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Industrial",
        "Culture": "French",
        "Affinity": "Scientist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Enlightened Thinking",
        "Emblematic unit": "Cuirassiers",
        "Emblematic quarter": "Exhibition Hall",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into 'Collective Minds' mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Industrial",
        "Culture": "Germans",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Iron Ordnance",
        "Emblematic unit": "Uboat",
        "Emblematic quarter": "Coking Works",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Industrial",
        "Culture": "Italians",
        "Affinity": "Aesthete",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Inspiring Virtuosos",
        "Emblematic unit": "Alpini",
        "Emblematic quarter": "Teatro",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Industrial",
        "Culture": "Mexicans",
        "Affinity": "Agrarian",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Fields of Gold",
        "Emblematic unit": "Soldaderas",
        "Emblematic quarter": "Hacienda",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Industrial",
        "Culture": "Persians",
        "Affinity": "Builder",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Mighty Works",
        "Emblematic unit": "Jazayerchis",
        "Emblematic quarter": "Caravanserai",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into 'Land Raiser' mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Industrial",
        "Culture": "Russians",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Land and Glory",
        "Emblematic unit": "Cossacks",
        "Emblematic quarter": "Sobor",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Industrial",
        "Culture": "Siamese",
        "Affinity": "Builder",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Gilded Orchids",
        "Emblematic unit": "Gatling Elephant",
        "Emblematic quarter": "Floating Market",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into 'Land Raiser' mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Industrial",
        "Culture": "Zulu",
        "Affinity": "Militarist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Warrior's Pride",
        "Emblematic unit": "Impi",
        "Emblematic quarter": "Warrior's Izindlu",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Contemporary",
        "Culture": "Americans",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "American Exceptionalism",
        "Emblematic unit": "Lightning",
        "Emblematic quarter": "Defense Agency",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Contemporary",
        "Culture": "Australians",
        "Affinity": "Builder",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Dream Weavers",
        "Emblematic unit": "All Terrain PMV",
        "Emblematic quarter": "Strip Mining Complex",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into 'Land Raiser' mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Contemporary",
        "Culture": "Brazilians",
        "Affinity": "Agrarian",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Lungs of the Planet",
        "Emblematic unit": "Jungle Brigades",
        "Emblematic quarter": "Agronomy Lab",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Contemporary",
        "Culture": "Chinese",
        "Affinity": "Merchant",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Silk Railroad",
        "Emblematic unit": "Guardians",
        "Emblematic quarter": "Congress",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Contemporary",
        "Culture": "Egyptians",
        "Affinity": "Aesthete",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Valley of Kings",
        "Emblematic unit": "Free Officers",
        "Emblematic quarter": "Archaeological Dig",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Contemporary",
        "Culture": "Indians",
        "Affinity": "Aesthete",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Economic Elephant",
        "Emblematic unit": "Peacekeepers",
        "Emblematic quarter": "Ashram",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Contemporary",
        "Culture": "Japanese",
        "Affinity": "Scientist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Blossoming Innovation",
        "Emblematic unit": "Reisen",
        "Emblematic quarter": "Robotics Lab",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into 'Collective Minds' mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Contemporary",
        "Culture": "Soviets",
        "Affinity": "Expansionist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Red Tide",
        "Emblematic unit": "Red Army Tank",
        "Emblematic quarter": "Arms Factory",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Contemporary",
        "Culture": "Swedes",
        "Affinity": "Scientist",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Prize Science",
        "Emblematic unit": "Stealth Corvette",
        "Emblematic quarter": "Research Institute",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into 'Collective Minds' mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Contemporary",
        "Culture": "Turks",
        "Affinity": "Agrarian",
        "Affinity Wiki Link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "People's Reforms",
        "Emblematic unit": "Stealthy Operative Missile",
        "Emblematic quarter": "Public School",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    }
];
