//Exporting cultures to be used in index.js
export {cultures};

//Array of objects containing cultures for Humankind and relevant attributes
let cultures = [
    {
        "Era": "Ancient",
        "Culture": "Assyrians",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Raid Masters",
        "Legacy trait info": "+1 Land Movement Speed on Unit, +5 Combat Strength bonus when Ransacking on Army",
        "Emblematic unit": "Assyrian Raiders",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Assyrian_Raiders",
        "Emblematic quarter": "Dunnu",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Dunnu",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Ancient",
        "Culture": "Babylonians",
        "Affinity": "Scientist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Brilliant Philosophers",
        "Legacy trait info": "+2 Science per researched technology on Capital.",
        "Emblematic unit": "Ṣäbu Ša Qašti",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/%E1%B9%A2%C3%A4bu_%C5%A0a_Qa%C5%A1ti",
        "Emblematic quarter": "Astronomy House",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Astronomy_House",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into Collective Minds mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Ancient",
        "Culture": "Egyptians",
        "Affinity": "Builder",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Grand Planners",
        "Legacy trait info": "+1 Industry on tiles producing industry, modify district industry cost by -10%.",
        "Emblematic unit": "Markabata",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Markabata",
        "Emblematic quarter": "Egyptian Pyramid",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Egyptian_Pyramid",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into Land Raiser mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Ancient",
        "Culture": "Harappans",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Fertile Inundations",
        "Legacy trait info": "+1 Food on tile producing food, +1 food on river.",
        "Emblematic unit": "Runner",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Runner",
        "Emblematic quarter": "Canal Network",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Canal_Network",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Ancient",
        "Culture": "Hittites",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Lust For War",
        "Legacy trait info": "+1 Combat strength.",
        "Emblematic unit": "Gigir",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Gigir",
        "Emblematic quarter": "Awari",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Awari",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Ancient",
        "Culture": "Mycenaeans",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Brutal upbringing",
        "Legacy trait info": "Modify unit industry cost by -20%, +25 exp on units created on cities or outposts.",
        "Emblematic unit": "Promachoi",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Promachoi",
        "Emblematic quarter": "Cyclopean Fortress",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Cyclopean_Fortress",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Ancient",
        "Culture": "Nubians",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Golden Dreams",
        "Legacy trait info": "+5 Money on luxury and strategic resource deposits.",
        "Emblematic unit": "Ta-Seti Archers",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Ta-Seti_Archers",
        "Emblematic quarter": "Meroe Pyramids",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Meroe_Pyramids",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Ancient",
        "Culture": "Olmecs",
        "Affinity": "Aesthete",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Natural Harmony",
        "Legacy trait info": "+1 Influence on territory.",
        "Emblematic unit": "Javelin Throwers",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Javelin_Throwers",
        "Emblematic quarter": "Olmec Head",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Olmec_Head",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Ancient",
        "Culture": "Phoenicians",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Trading Pioneers",
        "Legacy trait info": "+2 Money per trader on cities or outposts.",
        "Emblematic unit": "Bireme",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Bireme",
        "Emblematic quarter": "Haven",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Haven",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Ancient",
        "Culture": "Zhou",
        "Affinity": "Aesthete",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Harmonious Thought",
        "Legacy trait info": "+2 Stability on district.",
        "Emblematic unit": "Zhànche",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Zhànche",
        "Emblematic quarter": "Confucian School",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Confucian_School",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Classical",
        "Culture": "Achaemenid Persians",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Cyrus' Shadow",
        "Legacy trait info": "+2 City cap, +10 stability on cities or outposts.",
        "Emblematic unit": "Immortals",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Immortals",
        "Emblematic quarter": "Satrap Palace",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Satrap_Palace",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Classical",
        "Culture": "Aksumites",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Horn of Plenty",
        "Legacy trait info": "+2 Money on tiles producing money.",
        "Emblematic unit": "Shotelai",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Shotelai",
        "Emblematic quarter": "Great Obelisk",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Great_Obelisk",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Classical",
        "Culture": "Carthaginians",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Hard Bargainers",
        "Legacy trait info": "Modify all constructibles buyout cost by -25%.",
        "Emblematic unit": "War Elephant",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/War_Elephant",
        "Emblematic quarter": "Cothon",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Cothon",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Classical",
        "Culture": "Celts",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Druidic Lore",
        "Legacy trait info": "+2 Food per farmer on cities or outposts.",
        "Emblematic unit": "Gaesati",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Gaesati",
        "Emblematic quarter": "Nemeton",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Nemeton",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Classical",
        "Culture": "Goths",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Nimble Pillage",
        "Legacy trait info": "+2 Combat strength from ransacking on units, +2 influence on garrisons.",
        "Emblematic unit": "Gothic Cavalry",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Gothic_Cavalry",
        "Emblematic quarter": "Tumulus",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Tumulus",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Classical",
        "Culture": "Greeks",
        "Affinity": "Scientist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Socratic Methods",
        "Legacy trait info": "+2 Science per researcher on cities or outposts.",
        "Emblematic unit": "Hoplites",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Hoplites",
        "Emblematic quarter": "Amphitheatron",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Amphitheatron",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into Collective Minds mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Classical",
        "Culture": "Huns",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Formidable Steeds",
        "Legacy trait info": "+2 Combat strength on cavalry units.",
        "Emblematic unit": "Hunnic Horde",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Hunnic_Horde",
        "Emblematic quarter": "Ordu",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Ordu",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Classical",
        "Culture": "Mauryans",
        "Affinity": "Aesthete",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Guiding Light",
        "Legacy trait info": "+1 Influence on Emblematic districts, -10% on attach outpost cost.",
        "Emblematic unit": "Saṃnāhya",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Sa%E1%B9%83n%C4%81hya",
        "Emblematic quarter": "Stūpa",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/St%C5%ABpa",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Classical",
        "Culture": "Maya",
        "Affinity": "Builder",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Tireless Spirit",
        "Legacy trait info": "+2 Industry per worker on cities or outposts.",
        "Emblematic unit": "Noble Javelineers",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Noble_Javelineers",
        "Emblematic quarter": "K'uh Nah",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/K%27uh_Nah",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into Land Raiser mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Classical",
        "Culture": "Romans",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Legions Finest",
        "Legacy trait info": "+1 Unit slot available for each army, -30% army upkeep on armies.",
        "Emblematic unit": "Praetorian Guards",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Praetorian_Guards",
        "Emblematic quarter": "Triumphal Arch",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Triumphal_Arch",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Medieval",
        "Culture": "Aztecs",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Huitzilopochtli's Legacy",
        "Legacy trait info": "+2 Land movement speed on units, modify unit industry cost by -20%.",
        "Emblematic unit": "Jaguar Warriors",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Jaguar_Warriors",
        "Emblematic quarter": "Sacrificial Altar",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Sacrificial_Altar",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Medieval",
        "Culture": "Byzantines",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Master of Whispers",
        "Legacy trait info": "+5 money per alliance on all cities.",
        "Emblematic unit": "Varangian Guards",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Varangian_Guards",
        "Emblematic quarter": "Hippódromos",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Hipp%C3%B3dromos",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Medieval",
        "Culture": "English",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Serfs' Labor",
        "Legacy trait info": "+7 Food per number of attached territories on cities or outposts.",
        "Emblematic unit": "Longbowmen",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Longbowmen",
        "Emblematic quarter": "Stronghold",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Stronghold",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Medieval",
        "Culture": "Franks",
        "Affinity": "Aesthete",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Crown Lands",
        "Legacy trait info": "+10 Influence.",
        "Emblematic unit": "Franci Milites",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Franci_Milites",
        "Emblematic quarter": "Scriptorium",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Scriptorium",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Medieval",
        "Culture": "Ghanaians",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Life of Luxury",
        "Legacy trait info": "+5 Money per number of accesses to luxury and strategic resources.",
        "Emblematic unit": "Meharists",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Meharists",
        "Emblematic quarter": "Luxuries Market",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Luxuries_Market",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Medieval",
        "Culture": "Khmer",
        "Affinity": "Builder",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Servants of Magnificence",
        "Legacy trait info": "+3 Industry on Makers Quarter.",
        "Emblematic unit": "Dhanvī-gaja",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Dhanv%C4%AB-gaja",
        "Emblematic quarter": "Baray",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Baray", 
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into Land Raiser mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Medieval",
        "Culture": "Mongols",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Mounted Mayhem",
        "Legacy trait info": "100% Ransack gains on armies.",
        "Emblematic unit": "Mongol Horde",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Mongol_Horde", 
        "Emblematic quarter": "Orda",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Orda",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Medieval",
        "Culture": "Norsemen",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Stormborn",
        "Legacy trait info": "+3 Naval movement speed and +2 combat strength on naval units.",
        "Emblematic unit": "Langskip",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Langskip", 
        "Emblematic quarter": "Naust",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Naust",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Medieval",
        "Culture": "Teutons",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Spurred by Faith",
        "Legacy trait info": "+1 Money and +1 Science per state religion follower.",
        "Emblematic unit": "Teutonic Knights",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Teutonic_Knights", 
        "Emblematic quarter": "Kaiserdom",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Kaiserdom",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Medieval",
        "Culture": "Umayyads",
        "Affinity": "Scientist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Learned Friends",
        "Legacy trait info": "+5 Science per alliance on all cities.",
        "Emblematic unit": "Haras",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Haras",
        "Emblematic quarter": "Grand Mosque",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Grand_Mosque",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into Collective Minds mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Early Modern",
        "Culture": "Dutch",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Stock Wisdom",
        "Legacy trait info": "+1 Money per population on all cities.",
        "Emblematic unit": "Fluyt",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Fluyt",
        "Emblematic quarter": "V.O.C Warehouse",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/V.O.C_Warehouse",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Early Modern",
        "Culture": "Edo Japanese",
        "Affinity": "Aesthete ",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Shogun's Authority",
        "Legacy trait info": "+1 Influence per population on cities and outposts.",
        "Emblematic unit": "Naginata Samurai",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Naginata_Samurai",
        "Emblematic quarter": "Tera",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Tera",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Early Modern",
        "Culture": "Haudenosaunee",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Land of Plenty",
        "Legacy trait info": "+1 Food on exploitation.",
        "Emblematic unit": "Rotiskenrakehte",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Rotiskenrakehte",
        "Emblematic quarter": "Three Sisters Plantation",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Three_Sisters_Plantation",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Early Modern",
        "Culture": "Joseon",
        "Affinity": "Scientist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Hall of Wothies",
        "Legacy trait info": "+3 Science on tiles producing science.",
        "Emblematic unit": "Geobukseon",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Geobukseon",
        "Emblematic quarter": "Seowon",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Seowon",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into Collective Minds mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Early Modern",
        "Culture": "Ming",
        "Affinity": "Aesthete",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Grand Secretariat",
        "Legacy trait info": "-25% cost of enacting and revoking civics, +1 influence on territories.",
        "Emblematic unit": "Rocket Cart",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Rocket_Cart",
        "Emblematic quarter": "Grand Teahouse",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Grand_Teahouse",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Early Modern",
        "Culture": "Mughals",
        "Affinity": "Builder",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Imperial Magnificence",
        "Legacy trait info": "+2 Industry per number of territories in your sphere of influence on capitals.",
        "Emblematic unit": "Gajnal",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Gajnal",
        "Emblematic quarter": "Jama Masjid",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Jama_Masjid",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into Land Raiser mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Early Modern",
        "Culture": "Ottomans",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Supremacy of Fire",
        "Legacy trait info": "+3 combat strength and -50% industry cost for heavy weapons.",
        "Emblematic unit": "Janissaries",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Janissaries",
        "Emblematic quarter": "Sultan Camii",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Sultan_Camii",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Early Modern",
        "Culture": "Poles",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Deadly Ramparts",
        "Legacy trait info": "+10 District fortification and +2 stability on districts.",
        "Emblematic unit": "Winged Hussars",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Winged_Hussars",
        "Emblematic quarter": "Barbican",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Barbican",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Early Modern",
        "Culture": "Spanish",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Honor and Glory",
        "Legacy trait info": "+3 Combat strength on units starting their turn in a non-allied territory.",
        "Emblematic unit": "Conquistadores",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Conquistadores", 
        "Emblematic quarter": "Catedral Gótica",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Catedral_G%C3%B3tica",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Early Modern",
        "Culture": "Venetians",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Silver Tongues",
        "Legacy trait info": "+1 Money per number of trade routes on cities and outposts, +2 money per number of naval trade routes.",
        "Emblematic unit": "Galleass",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Galleass",
        "Emblematic quarter": "Botteghe Di Artisti",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Botteghe_Di_Artisti",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Industrial",
        "Culture": "Austro-Hungarians",
        "Affinity": "Aesthete ",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Emperor's Hand",
        "Legacy trait info": "+1 Influence on districts and Emblematic districts.",
        "Emblematic unit": "Evidenzbureau Agents",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Evidenzbureau_Agents",
        "Emblematic quarter": "Opernhaus",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Opernhaus", 
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Industrial",
        "Culture": "British",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Colonial Riches",
        "Legacy trait info": "+10 Money and +10 science per number of attached territories on capitals.",
        "Emblematic unit": "Redcoats",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Redcoats",
        "Emblematic quarter": "Colonial Office",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Colonial_Office",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Industrial",
        "Culture": "French",
        "Affinity": "Scientist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Enlightened Thinking",
        "Legacy trait info": "+10 Science on all cities.",
        "Emblematic unit": "Cuirassiers",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Cuirassiers",
        "Emblematic quarter": "Exhibition Hall",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Exhibition_Hall",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into Collective Minds mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Industrial",
        "Culture": "Germans",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Iron Ordnance",
        "Legacy trait info": "+3 Combat strength on naval and air units, -20% on units industry cost.",
        "Emblematic unit": "Uboat",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Uboat",
        "Emblematic quarter": "Coking Works",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Coking_Works",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Industrial",
        "Culture": "Italians",
        "Affinity": "Aesthete",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Inspiring Virtuosos",
        "Legacy trait info": "+10 Stability and +1 Influence on Commons Quarter and modify it's industry cost by -50%.",
        "Emblematic unit": "Alpini",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Alpini",
        "Emblematic quarter": "Teatro",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Teatro",
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Industrial",
        "Culture": "Mexicans",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Fields of Gold",
        "Legacy trait info": "+10% Food on all cities.",
        "Emblematic unit": "Soldaderas",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Soldaderas",
        "Emblematic quarter": "Hacienda",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Hacienda",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Industrial",
        "Culture": "Persians",
        "Affinity": "Builder",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Mighty Works",
        "Legacy trait info": "Reduces shared project and all constructibles industry cost by -25%.",
        "Emblematic unit": "Jazayerchis",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Jazayerchis",
        "Emblematic quarter": "Caravanserai",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Caravanserai",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into Land Raiser mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Industrial",
        "Culture": "Russians",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Land and Glory",
        "Legacy trait info": "+10 Exp per number of attached territories on all cities when creating a unit, +10 war support when capturing a city on relations.",
        "Emblematic unit": "Cossacks",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Cossacks", 
        "Emblematic quarter": "Sobor",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Sobor",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Industrial",
        "Culture": "Siamese",
        "Affinity": "Builder",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Gilded Orchids",
        "Legacy trait info": "+3 Industry per district on all cities, +1 money generated from on-going trade on all cities.",
        "Emblematic unit": "Gatling Elephant",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Gatling_Elephant",
        "Emblematic quarter": "Floating Market",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Floating_Market",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into Land Raiser mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Industrial",
        "Culture": "Zulu",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Warrior's Pride",
        "Legacy trait info": "+50% Health regeneration on units, +2 combat strengths on units starting their turn in allied territory.",
        "Emblematic unit": "Impi",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Impi",
        "Emblematic quarter": "Warrior's Izindlu",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Warrior%27s_Izindlu",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Contemporary",
        "Culture": "Americans",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "American Exceptionalism",
        "Legacy trait info": "+10 Influence on resources being sold, +1 money generated from on-going trade on cities and outposts.",
        "Emblematic unit": "Lightning",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Lightning",
        "Emblematic quarter": "Defense Agency",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Defense_Agency",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Contemporary",
        "Culture": "Australians",
        "Affinity": "Builder",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Builder",
        "Legacy trait": "Dream Weavers",
        "Legacy trait info": "+20 Industry on all cities.",
        "Emblematic unit": "All Terrain PMV",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/All_Terrain_PMV",
        "Emblematic quarter": "Strip Mining Complex",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Strip_Mining_Complex",
        "Affinity action": "Land Raiser",
        "Affinity action info": "Set city into Land Raiser mode where all the money and science of a city is converted into industry.",
        "Affinity bonus": "Pride",
        "Affinity bonus info": "Gain 10 stability when completing a District's construction."
    },
    {
        "Era": "Contemporary",
        "Culture": "Brazilians",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Lungs of the Planet",
        "Legacy trait info": "+3 Food on tiles producing food.",
        "Emblematic unit": "Jungle Brigades",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Jungle_Brigades", 
        "Emblematic quarter": "Agronomy Lab",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Agronomy_Lab",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Contemporary",
        "Culture": "Chinese",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Silk Railroad",
        "Legacy trait info": "+10% Money on all cities.",
        "Emblematic unit": "Guardians",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Guardians",
        "Emblematic quarter": "Congress",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Congress",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },
    {
        "Era": "Contemporary",
        "Culture": "Egyptians",
        "Affinity": "Aesthete",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Valley of Kings",
        "Legacy trait info": "+4 Influence on Emblematic districts.",
        "Emblematic unit": "Free Officers",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Free_Officers",
        "Emblematic quarter": "Archaeological Dig",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Archaeological_Dig", 
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Contemporary",
        "Culture": "Indians",
        "Affinity": "Aesthete",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Aesthete",
        "Legacy trait": "Economic Elephant",
        "Legacy trait info": "+3 Influence on territories, +10 money per number of territories in sphere of influence.",
        "Emblematic unit": "Peacekeepers",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Peacekeepers",
        "Emblematic quarter": "Ashram",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Ashram", 
        "Affinity action": "Cultural Blitz",
        "Affinity action info": "Spend money promoting patriotism in a territory, pushing back foreign influence and generating influence.",
        "Affinity bonus": "Grace",
        "Affinity bonus info": "Cultural Proximity is always maxed out."
    },
    {
        "Era": "Contemporary",
        "Culture": "Japanese",
        "Affinity": "Scientist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Blossoming Innovation",
        "Legacy trait info": "-20% On all technology cost when researching.",
        "Emblematic unit": "Reisen",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Reisen",
        "Emblematic quarter": "Robotics Lab",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Robotics_Lab",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into Collective Minds mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Contemporary",
        "Culture": "Soviets",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Red Tide",
        "Legacy trait info": "-20% On unit industry cost and +3 combat strength on units.",
        "Emblematic unit": "Red Army Tank",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Red_Army_Tank",
        "Emblematic quarter": "Arms Factory",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Arms_Factory",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Contemporary",
        "Culture": "Swedes",
        "Affinity": "Scientist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Scientist",
        "Legacy trait": "Prize Science",
        "Legacy trait info": "+1 Science per district on all cities, +3 science on Research Quarters.",
        "Emblematic unit": "Stealth Corvette",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Stealth_Corvette",
        "Emblematic quarter": "Research Institute",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Research_Institute_(district)",
        "Affinity action": "Collective Minds",
        "Affinity action info": "Set city into Collective Minds mode, where all industry and money output is converted into science.",
        "Affinity bonus": "Foresight",
        "Affinity bonus info": "+1 Era available to research."
    },
    {
        "Era": "Contemporary",
        "Culture": "Turks",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "People's Reforms",
        "Legacy trait info": "+1 Food per population on all cities.",
        "Emblematic unit": "Stealthy Operative Missile",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Stealthy_Operative_Missile",
        "Emblematic quarter": "Public School",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Public_School",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Ancient",
        "Culture": "Bantu",
        "Affinity": "Expansionist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Expansionist",
        "Legacy trait": "Harmonius Amalgamation",
        "Legacy trait info": "+2 Influence per number of adjacent empires on territories.",
        "Emblematic unit": "Bagèndí Pioneers",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Bag%C3%A8nd%C3%AD_Pioneers",
        "Emblematic quarter": "Mupíà Fields",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Mup%C3%AD%C3%A0_Fields",
        "Affinity action": "Under One Banner",
        "Affinity action info": "Forcibly annex territories occupied by other Empires outposts and admin centers.",
        "Affinity bonus": "Ambition",
        "Affinity bonus info": "Always able to trespass."
    },
    {
        "Era": "Classical",
        "Culture": "Garamantes",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Desert in Bloom",
        "Legacy trait info": "+5 Influence on main plaza if city is growing.",
        "Emblematic unit": "Javelin Riders",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Javelin_Riders",
        "Emblematic quarter": "Foggara",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Foggara",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },  
    {
        "Era": "Medieval",
        "Culture": "Swahili",
        "Affinity": "Merchant",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Merchant",
        "Legacy trait": "Coastal Haven",
        "Legacy trait info": "+10 Stability on harbor and +10 stability on harbors per adjacent regular district.",
        "Emblematic unit": "Mtepe",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Mtepe",
        "Emblematic quarter": "Bandari",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Bandari",
        "Affinity action": "Power Investor",
        "Affinity action info": "Use influence to marshal venture capital towards a resource deposit by creating an extractor or generating money.",
        "Affinity bonus": "Mediation",
        "Affinity bonus info": "Any resource bought via trade can be re-purchased by other Empires."
    },  
    {
        "Era": "Early Modern",
        "Culture": "Maasai",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Pastoral Prowess",
        "Legacy trait info": "-25% Population consumption on all cities.",
        "Emblematic unit": "Maasai Morans",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Maasai_Morans",
        "Emblematic quarter": "Enkang",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Enkang",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
    {
        "Era": "Industrial",
        "Culture": "Ethiopians",
        "Affinity": "Militarist",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Militarist",
        "Legacy trait": "Military Modernization",
        "Legacy trait info": "+5 Science on garrisons.",
        "Emblematic unit": "Oromo Cavalry",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Oromo_Cavalry",
        "Emblematic quarter": "Amba",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Amba",
        "Affinity action": "Iron Reserves",
        "Affinity action info": "Instantly raise Militia Armies in your cities.",
        "Affinity bonus": "Vigilance",
        "Affinity bonus info": "+30 War Support equilibrium value on relations."
    },
    {
        "Era": "Contemporary",
        "Culture": "Nigerians",
        "Affinity": "Agrarian",
        "Affinity wiki link": "https://humankind.fandom.com/wiki/Agrarian",
        "Legacy trait": "Glorious Overabundance",
        "Legacy trait info": "+2 Industry per farmer on cities, +1 farmer slots per oil on cities.",
        "Emblematic unit": "Mrap Vehicle",
        "Emblematic unit wiki link": "https://humankind.fandom.com/wiki/Mrap_Vehicle",
        "Emblematic quarter": "Oil Refinery",
        "Emblematic quarter wiki link": "https://humankind.fandom.com/wiki/Oil_Refinery",
        "Affinity action": "Greener Pastures",
        "Affinity action info": "Attract 1 population from each adjacent territory's city or outpost.",
        "Affinity bonus": "Community",
        "Affinity bonus info": "Gain 5 stability when gaining population."
    },
];
